# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='like',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_user', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='history',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
